import{a as b,S as E,i as a}from"./assets/vendor-a1ffffac.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const B="https://pixabay.com/api/",I="43965450-8f7f6d09b5429fd61500b9928";async function u(t,o=1,r=15){const n=`${B}?key=${I}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${r}`,e=await b.get(n);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}const f=document.getElementById("gallery"),m=document.getElementById("loader"),y=document.getElementById("no-results"),h=document.getElementById("load-more");let d;function v(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function $(){y.style.display="block"}function P(){y.style.display="none"}function R(){h.style.display="block"}function L(){h.style.display="none"}function w(t){const o=t.map(r=>`
    <a class="gallery-item" href="${r.largeImageURL}">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
      <div class="info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    </a>
  `).join("");f.insertAdjacentHTML("beforeend",o),d?d.refresh():d=new E(".gallery-item")}function S(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}let l=1,i="";document.getElementById("search-form").addEventListener("submit",async t=>{if(t.preventDefault(),i=document.getElementById("search-input").value.trim(),i===""){a.error({title:"Error",message:"Search query cannot be empty!"});return}l=1,v(),P(),p(),L();try{const o=await u(i,l);o.hits.length===0?$():(w(o.hits),R())}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{g()}});document.getElementById("load-more").addEventListener("click",async()=>{l+=1,p();try{const t=await u(i,l);t.hits.length===0?(L(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):(w(t.hits),S())}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
